name: 清理工作流与发布

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: '目标工作流名称'
        required: true
        type: string
      delete_releases:
        description: '同时删除发布和标签'
        type: boolean
        default: true
      confirm:
        description: '输入 DELETE 确认'
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    if: github.event.inputs.confirm == 'DELETE'

    steps:
      - name: 安装GitHub CLI
        run: |
          sudo apt update && sudo apt install gh -y
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: 获取工作流ID
        id: get_id
        run: |
          WORKFLOW_ID=$(gh api repos/${{ github.repository }}/actions/workflows | 
            jq -r ".workflows[] | select(.name == \"${{ github.event.inputs.workflow_name }}\") | .id")
          [ -z "$WORKFLOW_ID" ] && { echo "工作流未找到"; exit 1; }
          echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_OUTPUT

      - name: 删除工作流运行记录
        run: |
          gh api repos/${{ github.repository }}/actions/workflows/${{ steps.get_id.outputs.WORKFLOW_ID }}/runs |
            jq -r '.workflow_runs[]?.id' | xargs -I {} sh -c '
              echo "删除运行记录: {}"
              gh api --method DELETE repos/${{ github.repository }}/actions/runs/{}
              sleep 0.5
            '

      - name: 删除发布和标签
        if: github.event.inputs.delete_releases
        run: |
          gh api repos/${{ github.repository }}/releases |
            jq -r '.[]?.tag_name' | xargs -I {} sh -c '
              echo "删除发布与标签: {}"
              gh release delete {} -y
              gh api --method DELETE repos/${{ github.repository }}/git/refs/tags/{}
              sleep 0.5
            '

      - name: 完成清理
        run: echo "清理完成! 工作流ID: ${{ steps.get_id.outputs.WORKFLOW_ID }}"
    
